### ISSUE TITLE
Timing less than 5 min

### ISSUE THREAD

**Issue by toshibochan** [sfeakes/sprinklerd#1]
Hi have anyway to have time to set less than 5 min?

**Comment by sfeakes** [comment]
Do you mean from the Apple / HomeKit interface?   If you set it to 1 min in the web interface for the default runtime, then that will be reflected in the Apple home app, and can now be selected as a runtime.  (But you’ll only get 1,5,10 etc, no 2,3,4)
There wasn’t a way to select 1,2,3,4 min in the previous HomeKit version, but there was just an update, I’ll look and see if it’s now possible.

**Comment by sfeakes** [comment]
I just went over this, it's a limitation of the default Apple Home app.  If you use a different HomeKit app, then you will see other settings.
