### ISSUE TITLE
how update?

### ISSUE THREAD

**Issue by toshibochan** [sfeakes/sprinklerd#12]
how to update to the new version?

**Comment by sfeakes** [comment]
That will depend on how you got AqualinkD. Read the wiki, and that should tell you.
But you either use the aqua.sh script, or git.

**Comment by woodgieboodgie** [comment]
i installed via sudo ./release/install.sh

which script to run to update the SpinklerD?

**Comment by sfeakes** [comment]
I meant how you downloaded SprinklerD using git. Running ‘git pull’ from the director where you downloaded sprinklerd will usually do it, then run the install.sh again.
