### ISSUE TITLE
Zone 1 not working after apt-get update

### ISSUE THREAD

**Issue by toshibochan** [sfeakes/sprinklerd#14]
Zone 1 schedule not working after update the raspberry pi. I’m trying to change how long watering but always back to 0 min.

**Comment by toshibochan** [comment]
This happens in 2 raspberry pi zero

**Comment by sfeakes** [comment]
How are you changing the watering time (web ui / API / HomeKit)?  I assume all the other zones allow you to change watering time.  Also look in syslog see if there are any errors?

Other thing to do set set logging to file and turn on debug logging in sprinklerd config, then restart sprinklerd and look in that log for any errors.

**Comment by toshibochan** [comment]
I change in web ui. I change zone one to 5 min but Later when I go back to the Schedule page the tine is back to 0. This happening only in zone one. Other zone is okay.
![ED9AB737-EBA7-4659-9D5E-1A83E36734F4](https://user-images.githubusercontent.com/15816913/72686493-4e41ae00-3aaa-11ea-8db0-73361ce65942.jpeg)

**Comment by toshibochan** [comment]
Syslog 

Jan 19 19:51:08 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:08 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:09 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:09 DomoHouseSprinkler sprinklerd: action_web_request / type=calcfg&day=6&zone=1&time=5
Jan 19 19:51:09 DomoHouseSprinkler sprinklerd: Request type calcfg
Jan 19 19:51:09 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:09 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:10 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:10 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:11 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:11 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:12 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:12 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:13 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:13 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:13 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:13 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd: action_web_request / type=read
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd: Request type read
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd: WEB REQUEST read read
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:14 DomoHouseSprinkler sprinklerd
Jan 19 19:51:30 DomoHouseSprinkler sprinklerd: Checking if CRON needs to be updated
Jan 19 19:51:30 DomoHouseSprinkler sprinklerd: Updating CRON
Jan 19 19:51:50 DomoHouseSprinkler sprinklerd: action_web_request / type=homebridge
Jan 19 19:51:50 DomoHouseSprinkler sprinklerd: Request type homebridge
Jan 19 19:52:01 DomoHouseSprinkler cron[235]: (*system*sprinklerd) RELOAD (/etc/cron.d/sprinklerd)

**Comment by toshibochan** [comment]
In the debug log show updating but still not saving in the web ui

**Comment by toshibochan** [comment]
pi@DomoHouseSprinkler:~$ sudo cat /var/log/syslog | grep cron
Jan 20 07:11:01 DomoHouseSprinkler cron[235]: (*system*sprinkl
erd) RELOAD (/etc/cron.d/sprinklerd)
pi@DomoHouseSprinkler:~$ sudo cat /var/log/mesages | grep cron
 
cat: /var/log/mesages: No such file or directory
pi@DomoHouseSprinkler:~$ sudo cat /var/log/messages | grep cro
n
pi@DomoHouseSprinkler:~$ 
pi@DomoHouseSprinkler:~$

**Comment by toshibochan** [comment]
If I set zone 1 to 5 min to run now option in the schedule is set to 5 min automatically.
Is so strange behavior

**Comment by toshibochan** [comment]
![A4F6A109-1D09-4ADB-92A4-A287CC62BAD6](https://user-images.githubusercontent.com/15816913/72750267-3c770e00-3b71-11ea-96d7-0b3ae33a758f.jpeg)
![AB281D44-61C4-414A-925B-1644DD905FFF](https://user-images.githubusercontent.com/15816913/72750268-3c770e00-3b71-11ea-9cd1-143e136c28df.jpeg)

**Comment by sfeakes** [comment]
Sounds like it’s having issues writing the cron file.  
Can you check the permissions (including directory) and time date stamp on /etc/cron.d/sprinklerd .
Should have read/write to root and time stamp should be last time you updated the schedule.

**Comment by toshibochan** [comment]
Zone one not there

/etc/cron.d/sprinklerd                                     

#***** AUTO GENERATED DO NOT EDIT *****
0 6 * * 2 root /usr/bin/curl -s -o /dev/null 'localhost:80?type=cron&zone=2&runtime=4&state=on'
4 6 * * 2 root /usr/bin/curl -s -o /dev/null 'localhost:80?type=cron&zone=3&runtime=1&state=on'
0 6 * * 6 root /usr/bin/curl -s -o /dev/null 'localhost:80?type=cron&zone=2&runtime=3&state=on'
3 6 * * 6 root /usr/bin/curl -s -o /dev/null 'localhost:80?type=cron&zone=3&runtime=1&state=on'
0 0 * * * root /usr/bin/curl -s -o /dev/null 'localhost:80?type=sensor&sensor=chanceofrain&value=0'
0 0 * * * root /usr/bin/curl -s -o /dev/null 'localhost:80?type=sensor&sensor=raintotal&value=0'
#***** AUTO GENERATED DO NOT EDIT *****

**Comment by sfeakes** [comment]
So it’s not updating cron file, Go back to the logs, look for error.  What are the permissions on the file? Are you using a RO root filesystem?   Are you sure other zones are updating appropriately, as that file doesn’t match the UI screen shot you posted.

**Comment by toshibochan** [comment]
I add more zone and stop using zone 1. Is so strange only zone one is not working.

**Comment by sfeakes** [comment]
Can you post your cfg file?

**Comment by woodgieboodgie** [comment]
getting a similar issue. web server works, sprinklerd works, scheduler appears fine, but no zone 1. i am using a master valve so i have the seven zones.

**Comment by woodgieboodgie** [comment]
cron writes activity of any other zone, just not zone 1. pls help.

**Comment by woodgieboodgie** [comment]
![image](https://user-images.githubusercontent.com/52473319/81281451-33b53400-909d-11ea-941a-8f3e66a67f69.png)

manual trigger of zone 1 works

**Comment by woodgieboodgie** [comment]
Error loading platform requested in your config.json at position 2
[5/7/2020, 8:08:32 PM] Error: The requested platform 'sprinklerd' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)

**Comment by woodgieboodgie** [comment]
![image](https://user-images.githubusercontent.com/52473319/81282775-fb165a00-909e-11ea-81ad-c9e3ccbf37b5.png)

![image](https://user-images.githubusercontent.com/52473319/81282839-13867480-909f-11ea-92f0-4b54bbada82d.png)

**Comment by toshibochan** [comment]
Same for me but I wasn’t able to look into of lack of time. I just add more zone and I stop using zone 1 for now.

**Comment by woodgieboodgie** [comment]
Thanks, but i cant see Zone 8.  I have edited sprinklerd.conf, added an 8th zone and deleted all files in /accessories and /persist.. and restarted.  Did you modify anything else to get an additional zone working and visible through the browser?

**Comment by toshibochan** [comment]
I was using only 4 zones.
