### ISSUE TITLE
sudo npm install -g homebridge-sprinklerd Not working 404

### ISSUE THREAD

**Issue by DrJeff** [sfeakes/sprinklerd#20]
Getting 404 errors on installing of homebridge-sprinklerd

npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-sprinklerd - Not found

Are you using aqualinkd for sprinklerd?

**Comment by sfeakes** [comment]
Looks like npm has removed sprinklerd.    No idea why, will look into it

**Comment by DrJeff** [comment]
Thanks, thought I was crazy!

**Comment by sfeakes** [comment]
BTW.  The repo is there, just not the NPM side, still trying to figure that out.  but you can manually install.
https://github.com/sfeakes/homebridge-sprinklerd

**Comment by sfeakes** [comment]
OK fixed the NPM issue.
