### ISSUE TITLE
"Include in status"

### ISSUE THREAD

**Issue by woodgieboodgie** [sfeakes/sprinklerd#22]
It would be very handy to see the status of the sprinklers in the banner at the top of Homekit.  Can the "My Sprinklers' button display its status or even better the individual zones?
![thumbnail_IMG_2040](https://user-images.githubusercontent.com/52473319/94378131-40304b00-016a-11eb-8764-1ae81acd948c.png)

**Comment by sfeakes** [comment]
That’s a setting (Or fixed) in whatever app you are using for HomeKit on iOS device.

**Comment by woodgieboodgie** [comment]
Using Homekit and there is no setting (within the individual sprinkler objects) to be able to "Include in Home Status"
![thumbnail_Screenshot ](https://user-images.githubusercontent.com/52473319/94380872-9e652a00-017a-11eb-9dc2-b4409a1e0765.jpg)
