### ISSUE TITLE
MASTER_VALVE=0

### ISSUE THREAD

**Issue by toshibochan** [sfeakes/sprinklerd#3]
I set on sprinklerd.config MASTER_VALVE=0 but the master relay still turning ON. This is normal?

**Comment by sfeakes** [comment]
If you have zone 0 configured, that's seen as a master valve and will turn on with any other zone.  So if you don't have a master valve, start at zone 1.
Looking at it, the master_valve setting seems redundant.

**Comment by sfeakes** [comment]
I just checked the code. I had removed the master_valve part of the zone configuration, just forgot to take it out of the configuration file.  So that MASTER_VALVE=0 or 1 has no meaning, I've pulled it from the config file.

**Comment by toshibochan** [comment]
After the update the schedule not working anymore. I look in /etc/default/cron and EXTRA_OPTS=‘-l’ is enable.

**Comment by toshibochan** [comment]
When I delete the zone 0 the web not working

**Comment by toshibochan** [comment]
I reinstall all and the schedule is working now but when I delete zone 0 from conf file the web no show the other zones

**Comment by sfeakes** [comment]
There was a bug that causes some errors when zone 0 was not configured, I've fixed that and posted an update.

**Comment by toshibochan** [comment]
Thank you! And sorry for bothering you all the time! And sorry if my English is bad! I’m still learning.

**Comment by toshibochan** [comment]
I’m trying to set 2 zones to 0 min but keep going back to 10 min. Have any way to set to 0 min?

**Comment by toshibochan** [comment]
When you update the codes on github how you update your raspberry pi?

**Comment by sfeakes** [comment]
Go to the directory where you have SprinklerD and run the following 
```
git pull
sudo ./release/install.sh
```

**Comment by toshibochan** [comment]
Delete master valve now is okay.
Now only last thing is 0 min.

**Comment by sfeakes** [comment]
For default run time, 0 mins is not really valid, so thats why it's rejecting it and resetting to 1.
For the calendar schedule 0 is a valid runtime, so you should be able to set that to 0.

So I assume you are trying to set the default runtime to 0.  Can you let me know why you want to do that?  Maybe there is another option.

**Comment by toshibochan** [comment]
How to uninstall all?
I want uninstall all and install from scratch again.

**Comment by sfeakes** [comment]
if you download the latest version, I've added an uninstall option to the install script.
```./release/install.sh uninstall```

if you want to do it manually, remove these files.
```
/usr/local/bin/sprinklerd
/etc/sprinklerd.conf
/etc/systemd/system/sprinklerd.service
/etc/default/sprinklerd
/var/www/sprinklerd/<remove all sub directories>
/etc/avahi/services/sprinklerd.service
/etc/cron.d/sprinklerd
/var/cache/sprinklerd.cache
```

**Comment by toshibochan** [comment]
Hope one day you can find how to make “run now option” to set to “0 minute”. Because I have one zone in the room for in case of fire. So I don’t want this zone to run.

**Comment by sfeakes** [comment]
The latest update supports setting default run time to 0.

**Comment by toshibochan** [comment]
Super thanks! work great!
