### ISSUE TITLE
sorry for the stupid question 

### ISSUE THREAD

**Issue by hassman12** [sfeakes/sprinklerd#7]
hi,
kind of noob so... sorry
my homebridge is on a pi server
my watering system is far away
if i got this right then all i have to do in the server is to install 3 packages and update the platform and its ip in the configuration file. is this right? this means that the server has no idea how much zones there are and he pulls that information from the pi that is connected to the valves.
did i get the architecture correct in my head? 
thanks!!!

**Comment by sfeakes** [comment]
Yes you have that right.  (And the preferred way to install). The machine running home bridge and sprinklerd-homebridge plug-in can be on an entirely different system to a Pi running sprinklerd that’s connected to the valves.

This is how my setup is.

**Comment by hassman12** [comment]
Thank you!
