### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by swapper82** [sfeakes/sprinklerd#8]
Would be perfect if the software allowed no usage of Rpi GPIO and only Domoticz IDX devices as switches (i guess it only supports triggering from Domoticz not to domoticz) . I have all valves controlled by Domoticz but this applications integrations against homekit is so much cleaner since it uses "valves"

**Comment by swapper82** [comment]
Found https://github.com/goedh452/homebridge-http-sprinkler that solves the issue i have minus the nice webinterface though.

**Comment by sfeakes** [comment]
Glad you found a solution.  But, this is bi-directional with both Domoticz & Homekit, so it would do exactly what you want. But, it does used the GPIO memory address for the valve state, so just don;t connect a relayboard to the GPIO pins and it would do what you want (as long as you didn;t use the GPIO# for something else)
